### ISSUE TITLE
About smetana scores implemented in emp data.

### ISSUE THREAD

**Issue by zhanghaoyu9931** [cdanielmachado/cooccurrence#1]
Hello, I am working on community smetana of emp datasets using gems reconstructed by carveme. And I want to ask you some questions.
Firstly, I recurrent your experiment from reference: (2010) _Establishment and metabolic analysis of a model microbialcommunity for understanding trophic and electron accepting interactions of sub-surface anaerobic envs_. However, the smetana score using default parameters is not consistent with the experiment result from the reference. So, I want to know what extra things need to be done before computing the smetana score? For example, modify GEMs or manipulate the medium?

Secondly, I want to know which medium you have used to do the analysis of emp data in your recent paper? Did the medium need  to be modified according to the specific community you are computing or just set a default fixed medium?

Thank you very much for replying!

**Comment by cdanielmachado** [comment]
Regarding your first question, I am not sure if I understand what you mean with the smetana score not being consistent with the experimental results.

Regarding the EMP data, we did not specify any medium when running smetana. By default it calculates a minimal medium for the whole community.

**Comment by zhanghaoyu9931** [comment]
> Regarding your first question, I am not sure if I understand what you mean with the smetana score not being consistent with the experimental results.
> 
> Regarding the EMP data, we did not specify any medium when running smetana. By default it calculates a minimal medium for the whole community.

**Comment by zhanghaoyu9931** [comment]
> Regarding your first question, I am not sure if I understand what you mean with the smetana score not being consistent with the experimental results.
> 
> Regarding the EMP data, we did not specify any medium when running smetana. By default it calculates a minimal medium for the whole community.

thanks very much！
