### ISSUE TITLE
about competitive and cooperative co-occurring communities

### ISSUE THREAD

**Issue by zhanghaoyu9931** [cdanielmachado/cooccurrence#2]
Hello,

When I tried to reproduce your work, I met a problem. I noticed that in paper fig1, you said that 'Green and orange dots mark competitive and cooperative co-occurring communities, respectively'. And I found the green and orange dots correspond to the "bin_rnd_001" and "bin_rnd_01" files, respectively, I want to know how did you seperate the "bin_rnd_001" and "bin_rnd_01" files? Or based on what principle to divide competitive and cooperative co-occurring communities?

Thanks.

**Comment by cdanielmachado** [comment]
Hi. The communities in the `bin_rnd_001` and `bin_rnd_01` folders are the result of computing higher-order co-occurrence with two different thresholds for minimal species abundance per sample (0.01% and 0.1% respectively).

**Comment by zhanghaoyu9931** [comment]
Thanks very much!
